# Generated by Django 4.1.1 on 2022-11-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_checkout_checkoutproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='final',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='shipping',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total',
            field=models.IntegerField(),
        ),
    ]
