# Generated by Django 4.1.1 on 2022-11-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_buyer_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='rppid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
